version: '3'

services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./proxy/sites-enabled:/etc/nginx/conf.d
      - ./www/:/var/www/html/     
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - britosoftware.local
          - britosoftware.com.br

networks:
  default:
    ipam:
       driver: default
       config:
          - subnet: 172.28.0.0/16